### ISSUE TITLE
The playlist id always (mostly) equals the channel id

### ISSUE THREAD

**Issue by Crowbrammer** [naxels/youtube-channel-data#23]
For "uUU3jW7Y9Ak" (NileRed video):
```
Video id found: uUU3jW7Y9Ak
Channel Id: UCFhXFikryT4aFcLkLw2LBLA
Playlist Id: UUFhXFikryT4aFcLkLw2LBLA
```
For "zkw9aI1-feM" (PewDiePie video):

```
Video id found: zkw9aI1-feM
Channel Id: UC-lHJZR3Gqxm24_Vd_AJ5Yw
Playlist Id: UU-lHJZR3Gqxm24_Vd_AJ5Yw
```
The only thing that changes is "UC-" to "UU-". I haven't found an exception to this. I propose removing the playlist id search. 

The channel name is also available in the same request as for the channel id:

```
...
:localized {...}
:channelTitle "PewDiePie",
:defaultLanguage "en-US"}
```

**Comment by naxels** [comment]
https://stackoverflow.com/questions/19795987/youtube-channel-and-playlist-id-prefixes

Besides the more detailed question with exceptions above, what if it someday Youtube changes it's structure, then the app would stop working, while currently it will always work unless they change the API's responses.

**Comment by Crowbrammer** [comment]
I don't like YT's Data API maintainers😢
