### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by squromiv** [naxels/youtube-channel-data#38]
youtube-channel-data: 0.0.118
OS: Windows 8.1x64
Java: 8.351x64
![1](https://user-images.githubusercontent.com/15985877/205483564-49a8627b-a621-4885-8c88-f365e4f66793.png)

**Comment by naxels** [comment]
Hey @squromiv , thanks for letting me know.

It seems you are getting a 403 HTTP error, which is a Forbidden status according to Mozilla:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

Could you try the latest version, v0.0.130?
https://github.com/naxels/youtube-channel-data/releases/tag/v0.0.130

Here's what I get:
```
Video id found: WThBeu7kjJ4
Channel Id: UCUFnGWHIQvybwmR7XDh7-9A
Playlist Id: UUUFnGWHIQvybwmR7XDh7-9A
Channel title: Girl With The Dogs
Getting all playlist items.....
Playlist items found: 292
Getting all videos for duration data.....
Data saved to: output/Girl With The Dogs.csv
All done, exiting
```

If this doesn't work, maybe look at your API key and ensure it's authorized to make Youtube API calls.

**Comment by squromiv** [comment]
@naxels 
Recreated API key, downloaded v.0.0.130 and it looks as working now. Thanks a lot!

What [options] does it support? Is it possible to set another name for csv file? As for example - "temp.csv". How to change the output folder?

**Comment by naxels** [comment]
Thanks @squromiv for letting me know.

I'm closing this topic as it's resolved.

Let's move the other 2 questions into new discussions.
